
# Introduction

```{r parte_1, include=FALSE}
#### Code for I: Introduction ####
```

In general, fishing and/or the environment influence the large fluctuations experienced by the stocks, directly or indirectly affecting the magnitude of recruitment, which expresses through the entry of juveniles into the exploitable fraction [@Hsieh:2006aa; @Gomez:2012]. Likewise, the pre-recruitment phases can be sensitive to favorable or unfavorable environmental factors [@PERRY2010427; @PLANQUE2010403; @Hidalgo:2011aa]. Fluctuations in recruitment are caused not only by climate forcing and fishing but also due to ecological interactions such as predator-prey [@Ottersen2001; @Ciannelli; @Lindegren13672; @Travers-Trolet2014], particularly the shrimp-gadoid relationship [@Worm:2003; @DRINKWATER2010374; @Bjornsson2011; @B:2017aa].

Climate variability occurs on different time scales, from the seasonal, interannual cycle with irregular periods of 1 to 3 years associated with El Niño-Southern Oscillation (ENSO), aperiodic decadal variability between 5 to 50 years to centennial and longer-term periods [@Chavez217; @OVERLAND2010305; @PERRY2010427]. There is evidence that this variability influences the status and functioning of marine ecosystems and is closely related to population distribution, migration, and abundance [@Lehodey2006]. It has also been shown that fishing and other human activities have an impact on exploited and unexploited species [@Hsieh:2006aa; @PLANQUE2010403], and can modify the structure, size, and functioning of ecosystems [@Cury2000].

In the upwelling ecosystem of the Humboldt Current System, there have been seasonal and decadal changes in populations of small pelagic fish such as anchovy (_Engraulis ringens_) and sardine (_Sardinops sagax_), which demonstrate the almost immediate impact of the environment and synchrony over a wide latitudinal range [@ALHEIT2004201; @Cubillos2007a; @Yanez2008]. In the central-southern zone, the inter-annual variability of ENSO influences pelagic fish populations, for example, on the recruitment of the common sardine _Strangomera bentincki_ [@Gomez:2012]. El Niño and La Niña considerably modify the neritic environment, and we observed that in cold years (La Niña) there is an increase in the recruitment of typical sardines as a result of an increase in biological production [@PARADA2013]. In turn, climatic conditions influence faunal changes in plankton, zooplankton, and predators, mainly in the pelagic ecosystem [@Chavez217; @ALHEIT2004201; @vanderLingen2009; @Ayon2011; @XU2019103229], whose greater or lesser predation would have a direct effect on the benthic and demersal system [@Cury2000]. However, few studies have aimed at assessing the role of climate influence on benthic crustaceans distributed in deep waters over the continental platform and upper slope in the Humboldt Current System.

Nylon shrimp inhabits the continental platform and slope along the coast of Chile, between 200 and 500 m deep, associated with the Peru-Chile Subsurface Current flowing towards the pole, and the mixing of water masses between the Antarctic Intermediate Water (oxygenated and cold water, 11-12 ºC) and the Equatorial Subsurface Water (O$_2$ <1 ml L$^{-1}$, 12-13 ºC, 35 psu) [@Bahamonde:1970; @Arana2012; @Silva2012]. South of its distribution, river discharges, and upwelling events determine the availability of organic matter that could favor adult feeding. Likewise, the northward circulation of the Humboldt Current may explain the presence of juveniles in the north of its current distribution through processes of survival and recruitment by larval or juvenile dispersal [@Canales2016aa]. @Canales2016aa suggested that the shrimp population is likely to be a metapopulation structure with at least two subunits located north and south of 32°S, and whose connectivity would be explained by larval drift.

The shrimp fishery is located between 25ºS and 37º10'S, with two stock units [@MONTENEGRO201648; @CANALES20161]: a northern stock between 25ºS and 32ºS and a southern stock from 32ºS to 37º10'S (Fig. 1). The fishery involves a fleet of small industrial trawlers on the slope and the continental platform. The available data have made it possible to evaluate this resource from 1940 to 2015 through stock assessment models structured by length [@CANALES2016360]. Biomass indices are available from biomass evaluation by the swept area method, which show an increasing trend south of 32°S from 2006 [@Acunaetal2012]. According to [@Canales2016aa], positive trends in biomass could be influenced by the reduction in exploitation levels, the closure of some fishing areas since 2000, and by the depletion of Chilean hake (_Merluccius gayi gayi_) after 2003. The common hake is one of the most abundant and important predators of the demersal system in which shrimp and prawns live [@AranaWilliams1970; @CUBILLOS2007; @ArancibiaNeira2008], and it could be an additional factor influencing the variability of long-term recruitment of nylon shrimp.

According to the above, understanding and taking into account these sources of variability and their interactions represent a challenge for modern fisheries management. This work aimed to evaluate the hypothesis that the changes observed in the recruitment and biomass of nylon shrimp could be influenced by their population dynamics and the trophic interaction with common hake in a changing environment.