# Results

```{r parte_3, include=FALSE}
#### Code for III: Results ####
```

During the study period, the Humboldt Current Index (HCI) showed positive values in the periods 1970-1978 and 1997-2015, associated with a strengthening of the Pacific Anticyclone (Fig. 2). Between 1979 and 1996, the index remained negative, implying a period of warmer conditions. In turn, the Southern Oscillation Index (SOI) showed high inter-annual variability with El Niño events expressed with negative values of the SOI in the years 1972, 1977-1980, 1982-84, 1986-87, 1990-95, 1997-98, 2002-06, 2009, 2012, 2014 and 2015 (Fig. 2). It also identifies La Niña events (positive SOI values) in the years 1970, 1973-76, 1981, 1985, 1988-89, 1996, 1999-2001, 2007-08, 2010-11 and 2013. It should be noted that the length of a period in which negative values prevail between 1977 and 1997 is consistent with the same period identified in the HCI (Fig. 2).

Anomalies of recruitment for both stocks were similar to each other, showing negative fluctuations for the period from 1976 to 1998, and then remaining at positive values (Fig. 3A). However, we observe fluctuations in the spawning biomass of the northern stock that differs from that of the southern stock, the latter being more fluctuating throughout the period where negative values prevail for years similar to those observed in the recruitments (1976-1998) (Fig. 3B).

The Chilean hake biomass had a sustained increase from 1970 to mid-90s, dramatically decreasing from 2003 to 2004 and remained at low values from 2005 to 2015. Thus, we observed opposite trends between the spawning biomass of shrimp and the biomass of hake (Fig. 3C). Along with the above, from the model of predation hake-shrimp, the fraction of shrimp that goes from 0 to 3 years is depredated by all ages of hake, however, from age 2 + we observe a higher selectivity by hake over 4 years (Table 1).

The recruitment was not sensitive to the variability represented by SOI throughout the study period (Fig. 4). However, the sensitivity began to be significant and positive with the HCI, mainly between 1981-1987 and 1994-2013. The sensitivity of shrimp recruitment to changes in the biomass of hake showed a significant negative correlation in the periods 1974-1975, 1978-1988, 1991-1994, and from 2005 to 2013.


Out of nine GLM models, the models that considered shrimp spawning biomass and hake biomass in the year of recruitment, along with the climate indicator (HCI) in the year of annual class formation, better explained the variations in shrimp nylon recruitment (Table 2). The models M5 and M6, which include the Chilean hake direct effects on the year of recruitment plus either delayed or direct effects of the HCI, were the models that best represented the variation in shrimp recruitment. However, of the models selected, the model with the lowest AIC was the M6 model, which considered the negative effects of the Chilean hake biomass directly on the recruitment rate, and to a lesser extent the indirect effects of the HCI on the year of recruitment (Table 2).

The SEM analysis was based on the linear correlation between variables (Table 3) and showed that Chilean hake biomass (Hake) had significant negative effects on shrimp spawning biomass in the year of recruitment, as well as during annual-class formation (Hake.lag). To a lesser extent, we observed a lagged effect of the HCI on the spawning biomass (Fig. 5). There is evidence that the predator (Hake) was negatively and significantly related to the spawning biomass in the year of recruitment, and in the shrimp recruitment rate, in turn, Hake.lag and HCI.lag related to the shrimp spawning biomass with a two-year lag, the first negatively and significantly, and the second positively, but with low significance.

