# Discussion

```{r parte_4, include=FALSE}
#### Code for IV: Discussion ####
```

The challenge for modern fisheries management is to understand and take into account environmental variables and their interactions with exploited populations, leading to a more holistic view of the processes that influence the dynamics of exploited marine populations. In this study, we found that the recruitment of nylon shrimp is being influenced by the higher or lower biomass of Chilean hake, either through consumption of juveniles in the year of formation of the annual class or on adult spawners, in interaction with the interannual climate variability reflected through decadal variability expressed by the Humboldt Current Index during spawning.

The low influence of the spawning biomass itself on the recruitment rate and the climatic indicators HCI and SOI on shrimp spawning biomass in the year of formation of the year class are highlighted, both in the path diagram (SEM) and in the GAM models. The year-to-year changes between the indicators show the close relationship between the climate indices and negative values for HCI (periods of warm conditions) compared to existing positive values for SOI (El Niño phase). However, HCI only manifests itself as a decadal trend in the prevailing environmental conditions, while SOI represents the interannual variation ENSO (El Niño-Southern Oscillation) [@Blanco2004].

The climate variables analyzed here should be considered as indicating large-scale changes at the atmospheric level and in the ocean’s climate through ocean-atmosphere interaction. The influence at the habitat level of the nylon shrimp on the continental slope is unknown. However, climatic influence could likely influence the alteration in the circulation patterns of the Peru-Chile Subsurface Current and the distribution of physical properties associated with the mixing of present water mass, i.e., Subsurface Equatorial and Antarctic Intermediate [@S19791387; @Silva2012]. These water mass intensify or weaken during either El Niño or La Niña events, and influence the subsurface dynamics where the nylon shrimp live [@Hormazabal:2013].

The significance of these indices is conditional and increases when the incidence of Chilean hake on spawning biomass in the year of formation, and the recruitment rate is incorporated. Nevertheless, from GLM models, we conclude that Chilean hake would explain significantly the variations in the recruitment rate. Recruitment sensitivity analysis showed that Chilean hake presented more considerable significance, which expressed itself through a significant negative correlation in the periods 1973-1975, 1977-1986, and from 2005 to 2011. These results were consistent with [@Canales2016aa] in that the increase (decrease) in shrimp biomass could be modulated in part by the depletion (increase) of Chilean hake. The biomass of common hake showed an increasing trend in the first years of the series, with significant increases in 1972-1977, 1980-1984, 1991-1996, and 1998-2000 [@Tascheri2017]. These periods coincide with the years of the highest association between hake and the recruitment of nylon shrimp. Opposing trends between the biomasses of hake and spawning biomasses of nylon shrimp were consistent with findings by @Worm:2003, whom showed that the abundance of northern shrimp (_Pandalus Borealis_) was negatively related to Atlantic cod (_Gadus morhua_) populations. These authors found that cod correlated with temperature, and they found that changes in predator populations can have substantial effects on prey populations in the ocean food networks and that the intensity of these interactions can be sensitive to changes in mean ocean temperature [@Worm:2003]. @Bjornsson2011 found that seasonal migratory activity of immature _G. morhua_ was affected both by the location of the local shrimp stock, and the seasonal and spatial differences in temperature. 

We found that the incidence of shrimp in the diet of hake is generally low [@Arancibiaetal1998; @Cubillosetal:2003mgayi], which could be related to deeper distribution of naylon shrimp. Nevertheless, size selectivity coefficients indicated that common hake from 2 to 4 years of age preys preferentially on 1 to 3-year-old nylon shrimp (shrimp juveniles, recruits, and spawning individuals, as reported by @Canalesetal:1999). These results are consistent with those found by @CUBILLOS2007, who conclude through the same analysis that hakes over 4 years old prey on red squat lobster (_Pleuroncodes monodon_) and yellow squat lobster (_Cervimunida johni_) over 2 years old. It is important to note that after 2003, the biomass of Chilean hake decreased significantly and there was also a juvenilization of the age structure, supported by specimens from 2 to 5 years of age, in addition to a decrease in the size at maturity [@ArancibiaNeira2008; @Lilloetal2015]. These demographic changes in the predator could relax probable predation effects favoring the recruitment of nylon shrimp.

With the above, studies of the concurrent fauna in the direct assessment cruises of Chilean hake, shrimp and squat lobster, point to nylon shrimp as one of the main species within the faunal group of the demersal assembly [@Lilloetal2015; @Acunaetal2019; @Montero:2020aa], the same occurs in the direct assessment cruises of shrimp, where common hake and prawns, make up the main species associated with the captures, with the former showing the most significant recurrence in the captures throughout the entire sampling area [@Acunaetal:2002; @Aranaetal:2006; @Acunaetal2012; @Acunaetal2019].

The aforementioned suggests that the interaction in the biological components would have a more significant impact on the biological processes of the component species than the prevailing environmental conditions. Finally, we concluded that the recruitment of nylon shrimp is influenced by Chilean hake, either through the consumption of juveniles in the year of recruitment or on adult spawners, in interaction with decadal climate variability.
